### ISSUE TITLE
[NextGen] - Data Engineering - Trial Use OHS Components (fhir-data-pipes, FHIR views)

### ISSUE THREAD

**Issue by muhammad-levi** [sid-indonesia/data-analytics#2]
https://github.com/google/fhir-data-pipes/wiki#quick-start-guide

![Image](https://github.com/sid-indonesia/data-analytics/assets/78334846/a6dcdf3f-91e6-4e7e-94b7-a766536d5a42)

# Steps

- [x] Create GCE instance, name it "open-health-stack-components" or else
- [x] Deploy OHS components using `docker-compose` in the GCE VM instance
- [x] Connect the Apache Spark SQL to Metabase for further data exploration

**Comment by muhammad-levi** [comment]
@leo0263 
![Image](https://github.com/sid-indonesia/data-analytics/assets/78334846/146df789-6b5c-4b50-a0cf-ea8491ab48e4)

https://console.cloud.google.com/compute/instances?onCreate=true&authuser=3&project=nextgen-398301

**Comment by muhammad-levi** [comment]
FHIR Data Pipes' Control Panel can be accessed from SID's Remote Server "sas.sid-indonesia.org" at address fhir-data-pipes.sid-indonesia.org:8090 (make sure the DNS A Record pointing to the right public IP address of the GCE VM instance `open-health-stack-components`)

**Comment by muhammad-levi** [comment]
Opened an issue in Google's FHIR Data Pipes repo https://github.com/google/fhir-data-pipes/issues/925

**Comment by muhammad-levi** [comment]
Connected the Spark SQL to Metabase in here
https://dashboards.sid-indonesia.org/browse/25-1-ohs-hapi-fhir-team-based-care-apache-spark-sql
